# Dockerfile-http-server
FROM node:18

# Install http-server globally
RUN npm install -g http-server

# Copy frontend files into the image
COPY frontend /usr/src/app/frontend

# Set working directory
WORKDIR /usr/src/app/frontend

# Expose port for http-server
EXPOSE 8081

# Start http-server
CMD ["http-server", ".", "-p", "8081"]
