version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: votre_nouveau_mot_de_passe
      DB_NAME: exchange_rates_db

  http-server:
    build:
      context: .
      dockerfile: Dockerfile-http-server
    ports:
      - "8081:8081"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: votre_nouveau_mot_de_passe
      MYSQL_DATABASE: exchange_rates_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
